### PR TITLE
Add/cloud resources

### PR DESCRIPTION
**Pull request by nerdeveloper**

### CODE REVIEW

**Comment by ghost** [comment]
Hi @nerdeveloper , these are awesome resources, however, most of the resources are paid. I believe the focus is on _Free Courses/Tutorials_. Could you please add *Free Resources* instead.
🙏 _Thank you_

**Comment by BolajiAyodeji** [comment]
> Hi @nerdeveloper , these are awesome resources, however, most of the resources are paid. I believe the focus is on _Free Courses/Tutorials_. Could you please add _Free Resources_ instead.
>  _Thank you_

I think he added a combination of both. The YouTube videos are free but the courses are paid. We'll have to update them.

**Review by BolajiAyodeji — CHANGES_REQUESTED** [review]
Thanks for this amazing PR chief! Any possibilities of adding FREE courses? My bad for not mentioning this earlier.

**Comment by nerdeveloper** [comment]
> Thanks for this amazing PR chief! Any possibilities of adding FREE courses? My bad for not mentioning this earlier.

Okay, You hardly see people give good courses that are free in cloud computing, just tutorials. But I'd dig up and see what I can find. Give me a few minutes/hours

**Comment by BolajiAyodeji** [comment]
> > Thanks for this amazing PR chief! Any possibilities of adding FREE courses? My bad for not mentioning this earlier.
> 
> Okay, You hardly see people give good courses that are free in cloud computing, just tutorials. But I'd dig up and see what I can find. Give me a few minutes/hours

Thanks a lot, chief. Pro tip: You might find some great start videos on YouTube and some tutorial articles. Apologies for the inconvenience.

**Comment by nerdeveloper** [comment]
Please @BolajiAyodeji check again

**Review by BolajiAyodeji — APPROVED** [review]
Thanks for this PR chief!

**Pull request merged**
